### ISSUE TITLE
field highlighting on Maps

### ISSUE THREAD

**Issue by drtimwright** [gmandnepr/IdeaConcordionSupport#2]
Hi there,

I regulary return Map classes from my fixture methods:

    public Map<String, Object> getLastGuiMessage() { ... }

In the HTML spec, the field access is highlighted with an error "field not found":

                <span c:set="#guiMessage = getLastGuiMessage()"/>
                <div c:echo="#guiMessage.bodyRaw"></div>

![2015-09-22 11_35_35-pceftpos - c__users_t_timw7_documents_pceftpos_vips - ips-service - _ips-](https://cloud.githubusercontent.com/assets/7540034/10007982/1202c344-611e-11e5-99aa-a9cd75955b99.png)

**Comment by gmandnepr** [comment]
Hi Tim,

Thanks for your feed back. That is the feature I started working on just 2
hours ago :) So it will not be highlighted as errors. I am planing to
finish that in two days.
Also I am going to create warning inspection (you will be able to disable
that in the properties) saying this is key in the map.
Warning is going to say that this is dynamic typing trick and you should
probably refactor that into inner class to have a structure and to be
statically typed.

Please let me know what do you think about this.

Thanks,
Evgen


2015-09-21 19:35 GMT-04:00 Tim Wright <notifications@github.com>:

**Comment by drtimwright** [comment]
That seems very sensible - I like the warning idea as well (and I probably
should refactor my code too :)

Tim

On 22 September 2015 at 12:20, Ievgen Degtiarenko <notifications@github.com>
wrote:

> Hi Tim,
>
> Thanks for your feed back. That is the feature I started working on just 2
> hours ago :) So it will not be highlighted as errors. I am planing to
> finish that in two days.
> Also I am going to create warning inspection (you will be able to disable
> that in the properties) saying this is key in the map.
> Warning is going to say that this is dynamic typing trick and you should
> probably refactor that into inner class to have a structure and to be
> statically typed.
>
> Please let me know what do you think about this.
>
> Thanks,
> Evgen
>
>
> 2015-09-21 19:35 GMT-04:00 Tim Wright <notifications@github.com>:
>
> > Hi there,
> >
> > I regulary return Map classes from my fixture methods:
> >
> > public Map<String, Object> getLastGuiMessage() { ... }
> >
> > In the HTML spec, the field access is highlighted with an error "field
> not
> > found":
> >
> > <span c:set="#guiMessage = getLastGuiMessage()"/>
> > <div c:echo="#guiMessage.bodyRaw"></div>
> >
> > [image: 2015-09-22 11_34_38-pceftpos -
> > c__users_t_timw7_documents_pceftpos_vips - ips-service - _ips-]
> > <
> https://cloud.githubusercontent.com/assets/7540034/10007968/f6d4ff56-611d-11e5-9420-873f373c2e7b.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gmandnepr/IdeaConcordionSupport/issues/2>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gmandnepr/IdeaConcordionSupport/issues/2#issuecomment-142144809>
> .
>



-- 
Tim
021 251 5593
http://www.linkedin.com/in/drtimwright

**Comment by gmandnepr** [comment]
Fixed in version 20150922
